<option value="1">Computer Fundamentals</option>
<option value="2">Discrete Mathematics</option>
<option value="3">Physics</option>
<option value="4">Calculus</option>
<option value="5">English</option>
<option value="6">Digital Logic Design</option>
<option value="7">Structured Programming</option>
<option value="8">Linear Algebra</option>
<option value="9">Electrical Circuits</option>
<option value="10">Bangladesh Studies</option>
<option value="11">Object Oriented Programming</option>
<option value="12">Data Structure and Algorithms-I</option>
<option value="13">Computer Architecture</option>
<option value="14">Probability and Statistics</option>
<option value="15">Electronics</option>
<option value="16">Data Structure and Algorithms-II</option>
<option value="17">Numerical Methods</option>
<option value="18">Theory of Computing</option>
<option value="19">Database</option>
<option value="20">Accounting</option>
<option value="21">Data Communication</option>
<option value="22">Operating System</option>
<option value="23">Compiler Design</option>
<option value="24">Information System Design</option>
<option value="25">Artificial Intelligence</option>
<option value="26">Computer Networking</option>
<option value="27">Software Engineering</option>
<option value="28">Web and Mobile Application Development</option>
<option value="29">Machine Learning</option>
<option value="30">Engineering Economics</option>
<option value="31">Microprocessor and Microcomputer</option>
<option value="32">Digital System Design</option>
<option value="33">Computer Security</option>
<option value="34">Entrepreneurship of ICT</option>
<option value="35">Computer Graphics</option>
<option value="36">Introduction to Data Science</option>
<option value="37">Introduction to Data Mining and Warehousing</option>
<option value="38">Advanced Algorithms</option>
<option value="39">Bioinformatics</option>
<option value="40">Information Retrieval</option>
<option value="41">Graph Theory</option>
<option value="42">Human Computer Interaction</option>
<option value="43">Wireless Networks</option>
<option value="44">Computer Vision and Image Processing</option>
<option value="45">VLSI Design</option>
<option value="46">Natural Language Processing</option>
<option value="47">Computer Ethics</option>
<option value="48">Simulation & Modeling</option>
<option value="49">Digital Signal Processing</option>
<option value="50">Introduction to Robotics</option>
<option value="51">Communication Systems</option>
<option value="52">Parallel & Distributed Systems</option>